// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwiuvnikqfztukigegpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aXV2bmlrcWZ6dHVraWdlZ3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDczNDUsImV4cCI6MjA2NjAyMzM0NX0.JS6vVG9VttpsHR_feH1I_O6ihsgoJwrvnuGcLXY2K-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});